# Generated by Django 6.1 on 2026-08-16 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='chat.chatmessage')),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'read_at'], name='chat_messag_user_id_8ceef9_idx')],
                'unique_together': {('message', 'user_id')},
            },
        ),
    ]
