# Generated by Django 6.1 on 2026-08-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='LmsNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_role', models.CharField(max_length=20)),
                ('recipient_id', models.IntegerField()),
                ('from_role', models.CharField(max_length=20)),
                ('from_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=300)),
                ('channel', models.CharField(max_length=80)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
