# Generated by Django 6.1 on 2026-08-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('kind', models.CharField(default='dm', max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=300)),
                ('from_user_id', models.IntegerField()),
                ('channel', models.CharField(max_length=80)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user_id', 'read_at'], name='notificatio_user_id_47e85c_idx')],
            },
        ),
    ]
